### PR TITLE
Plugins Menu Overhaul and Stats Preparation

### PR DESCRIPTION
**Pull request by WesternGamer**
Plugins menu is now completely overhauled. I added code in PluginData in preparation for the stats code as it would be easier to implement the system in PluginData than in the menu class. For more info about that code, go to region IMPORTANT starting at line 77 in PluginData.cs.

Have a good day!

### CODE REVIEW

**Comment by austinvaness** [comment]
Why were the checkboxes in the list removed? Clicking each one individually doesnt seem like a good replacement

**Comment by WesternGamer** [comment]
It is because there was an bug where the checkboxes in the list would not
select in the correct place and I did not feel like fixing that issue
because I thought that the issue is in the list control. There is most
likely a way to fix the checkbox issue and leave the checkboxes in the list
but it is just a few extra seconds to select each one as you would usually
don't try to select all plugins in the list. You can revert that change if
you feel like that you can fix the checkbox issue.

**Comment by WesternGamer** [comment]
Looking at your code changes, thanks for finding a more proper solution in ChangePluginEnableStatus. I did not know you can change the cell value like that.

**Comment by WesternGamer** [comment]
Please rereview to PR as some changes has been made.

**Review by austinvaness — APPROVED** [review]

**Pull request merged**
